version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-syntax-analyzer
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ACTIVE_SWAGGER=true
    restart: always